FROM python:3.12

ENV PYTHONUNBUFFERED 1

RUN \
   apt-get -y update  && apt-get -y upgrade && apt-get -y dist-upgrade 

RUN apt-get update

WORKDIR /code/sweet

COPY requirements.txt /code/sweet/

RUN \
    pip install --upgrade pip setuptools wheel \
    && pip install --upgrade pip \
    && pip install --upgrade pip setuptools wheel \
    && pip install -r requirements.txt

COPY . ./sweet


CMD ["celery", "-A", "sweet.celery", "worker", "--loglevel=INFO"]