# Generated by Django 5.0.6 on 2024-08-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desert', '0003_alter_recipe_options_recipe_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='language',
            field=models.CharField(blank=True, choices=[('AZ', 'AZ'), ('EN', 'EN'), ('RU', 'RU')], max_length=4, null=True),
        ),
    ]
