# Generated by Django 5.0.6 on 2024-08-14 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desert', '0004_comment_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='category_photos/')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desert.category')),
            ],
        ),
    ]
