# Generated by Django 5.0.6 on 2024-08-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desert', '0005_categoryphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryphoto',
            options={'verbose_name': 'Category Photo', 'verbose_name_plural': 'Category Photos'},
        ),
        migrations.AlterField(
            model_name='categoryphoto',
            name='img',
            field=models.ImageField(upload_to='category_photos/%Y/%m/%d'),
        ),
    ]
