# Generated by Django 5.0.6 on 2024-08-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desert', '0006_alter_categoryphoto_options_alter_categoryphoto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryphoto',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='desert.category'),
        ),
    ]
