# Generated by Django 5.0.6 on 2024-08-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desert', '0013_rename_description_recipe_ingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_main', models.BooleanField(default=False)),
                ('is_sub', models.BooleanField(default=False)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_page/icons/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
