# Generated by Django 5.0.6 on 2024-08-31 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desert', '0014_categorypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='super_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desert.categorypage'),
        ),
    ]
