# Generated by Django 5.1.1 on 2024-09-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desert', '0016_recipepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='CategoryPage',
        ),
        migrations.DeleteModel(
            name='RecipePage',
        ),
    ]
