# Generated by Django 5.1.1 on 2024-09-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desert', '0019_rename_about_comment_text_rename_author_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
