# Generated by Django 5.1.1 on 2024-09-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desert', '0021_recipe_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
