# Generated by Django 5.1.1 on 2024-09-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desert', '0024_remove_recipe_is_paid_remove_recipe_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialrecipe',
            name='language',
            field=models.CharField(blank=True, choices=[('AZ', 'AZ'), ('EN', 'EN'), ('RU', 'RU')], max_length=4, null=True),
        ),
    ]
